# Generated by Django 5.1.2 on 2024-12-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinpoint', '0002_jwttoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JWTToken',
        ),
    ]
