# Generated by Django 5.1.4 on 2024-12-16 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinpoint', '0005_alter_package_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_value',
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text='Current location of the operator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_operators', to='pinpoint.location'),
        ),
    ]
