# Generated by Django 5.1.4 on 2024-12-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinpoint', '0006_remove_location_timestamp_remove_order_total_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='operatorrouteassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatorrouteassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='ASSIGNED', max_length=15),
        ),
        migrations.AddField(
            model_name='route',
            name='geometry',
            field=models.JSONField(blank=True, help_text='GeoJSON or polyline for the route', null=True),
        ),
    ]
