# Generated by Django 5.1.4 on 2024-12-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinpoint', '0008_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
